version: '2'

services:
  http-server:
    build: .
    image: alecholmez/http-server
    depends_on:
      - mongo
    volumes:
      - .:/go/src/github.com/alecholmez/testHttpServer
    command: /bin/sh -c "/go/bin/govendor sync; go build -o /go/bin/main && /go/bin/main"
    expose:
      - 8080
    ports:
      - "8080:8080"

  mongo:
    image: mongo
