version: '2'

services:
  http-server:
    build: .
    image: alecholmez/http-server:latest
    depends_on:
      - mongo
    command: /bin/sh -c "/go/bin/govendor sync; go build -o /go/bin/h2tp /h2tp && /go/bin/ht2p"
    expose:
      - 6060
    ports:
      - "6060:6060"

  mongo:
    image: mongo:latest
